- job:
    block-downstream: false
    block-upstream: false
    builders:
    - copyartifact:
        exclude-pattern: null
        filter: '**/*/kubeconfig,cluster-config.txt,cluster-dir.tar.gz'
        flatten: true
        project: dev-svc-create-daily-custer-4.4
        target: '4.4'
        which-build: last-successful
    - copyartifact:
        exclude-pattern: null
        filter: '**/*/kubeconfig,cluster-config.txt,cluster-dir.tar.gz'
        flatten: true
        project: dev-svc-create-daily-custer-4.5
        target: '4.5'
        which-build: last-successful
    concurrent: false
    disabled: false
    name: dev-svc-cluster-latest-kubeconfig
    project-type: freestyle
    properties:
    - copyartifact:
        projects: update-secrets_rose-sanbox-1
    - build-discarder:
        artifact-days-to-keep: -1
        artifact-num-to-keep: -1
        days-to-keep: -1
        num-to-keep: 1
    publishers:
    - archive:
        allow-empty: false
        artifacts: '**/*'
        case-sensitive: true
        default-excludes: true
        fingerprint: false
        only-if-success: false
    triggers:
    - reverse:
        jobs: dev-svc-create-daily-custer-4.4, dev-svc-create-daily-custer-4.5
    wrappers: []
